name: autoconfig
services:
  autoconfig-app:
    build:
      context: .
    container_name: autoconfig-app
    restart: unless-stopped
    ports:
      - 4243:5000
    # ONLY for testing
    #volumes:
    #  - ./src:/srv/flask_app
    #entrypoint: ["tail", "-f", "/dev/null"]
